spring:
 cloud:
  gateway:
   routes:
    - id: farmerModule
      uri: http://localhost:8081/
      predicates:
      - Path=/farmer/**
    - id: traderModule
      uri: http://localhost:8082/
      predicates:
      - Path=/dealer/**

